spring:
  datasource:
    username: comic
    password: comic
    url: jdbc:mysql://localhost:3306/comic
   
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    
  sql:
    init:
      mode: always      